### PR TITLE
Split MultiSelector into CompositeSelector and MultiSelector with distinct semantics

### PR DESCRIPTION
**Pull request by proycon**
This sprang from discussion with @dirkroorda in #7: The new CompositeSelector is more like the old MultiSelector, the new MultiSelector has a different interpretation.

Most important excerpt from the text (`README.md`):

* ``MultiSelector``  - A selector that consists of multiple other selectors to select multiple targets. This *MUST* be interpreted as the annotation applying to each target *individually*, without any relation between the different targets. Leaving one out or adding one *MUST NOT* affect the interpretation of any of the others nor of the whole. This is a way to express multiple annotations  as one, a more condensed representation. This selector *SHOULD* be used sparingly in your modelling, as it is generally *RECOMMENDED* to simply use multiple `Annotation`s instead. In STAM, even with multiple annotations, you benefit from the fact that multiple annotations may share the same `AnnotationData`, and can therefore easily retrieve all annotations that share particular data.
* ``CompositeSelector``  - A selector that consists of multiple other selectors, used to select more complex targets that transcend the idea of a single simple selection. This *MUST* be interpreted as the annotation applying equally to the conjunction as a whole, its parts being inter-dependent and for any of them it goes that they *MUST NOT* be omitted for the annotation to make sense. The interpretation of the whole relies on all its parts. Note that the order of the selectors is not significant (use a `DirectionalSelector` instead if they are). When there is no dependency relation between the selectors, you *MUST* simply use multiple `Annotation`s or a `MultiSelector` instead. When grouping things into a set, do use a `CompositeSelector`, as the set as a whole is considered a composite entity.

### CODE REVIEW

**Comment by dirkroorda** [comment]
You advise to use MultiSelector sparingly and to use multiple annotations with the same body instead, since the body can be shared among annotations.

I just wonder what happens when you make annotations of annotations.

Suppose you model lexemes as one annotation per lexeme with a MultiSelector target to each of its occurrences.

Suppose then that you want to annotate lexemes with semantic labels.

For each semantic label you can make an annotation with the label as body and a MultiSelector to each of the lexemes in question.

If you had modelled the lexemes as multiple annotations per lexeme, them, in order to target the semantic label annotations, you could again make a set of many semantic annotations per label: to each occurrence of each lexeme that has the label.

But that would have all sorts of disadvantages.

I would say: leave it to the modeller, without too much advice. In some cases, you want to extract the common things aggressively, and then MultiSelector is better than many annotations.

In other cases many annotations with the same body could be the most simple thing to do.

**Comment by dirkroorda** [comment]
Maybe we need two kinds of documents: a terse specification. And a longer story of with examples that show the intentions behind the model and the benefits of the various choices you have.

**Comment by proycon** [comment]
I see what you mean in the lexeme situation and higher-order annotations, that's a good example. 

> I would say: leave it to the modeller, without too much advice. In some cases, you want to extract the common things aggressively, and then MultiSelector is better than many annotations.

Agreed, I'll adapt the text and water it down to just a slight 'hint' that even if you have multiple annotations, they may share the same data (and therefore be easily referenced in that way).

> Maybe we need two kinds of documents: a terse specification. And a longer story of with examples that show the intentions behind the model and the benefits of the various choices you have.

We already have a separate separate examples document
(https://github.com/annotation/stam/blob/master/examples/README.md), which
could be made more elaborate and explain benefits/consequences of
various choices. I think that'd be a good idea yes.

**Comment by proycon** [comment]
Merging this one now after the changes, we can always adapt more later if needed

**Pull request merged**
